# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'basicEmitter.ui'
#
# Created: Sun Mar 04 15:23:33 2012
#      by: PyQt4 UI code generator 4.7.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_basicEmitterWidget(object):
    def setupUi(self, basicEmitterWidget):
        basicEmitterWidget.setObjectName("basicEmitterWidget")
        basicEmitterWidget.resize(303, 337)
        self.gridLayout_2 = QtGui.QGridLayout(basicEmitterWidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.emitterTypeLabel = QtGui.QLabel(basicEmitterWidget)
        self.emitterTypeLabel.setObjectName("emitterTypeLabel")
        self.gridLayout_2.addWidget(self.emitterTypeLabel, 0, 0, 1, 1)
        self.emitterType = QtGui.QComboBox(basicEmitterWidget)
        self.emitterType.setObjectName("emitterType")
        self.emitterType.addItem("")
        self.emitterType.addItem("")
        self.emitterType.addItem("")
        self.emitterType.addItem("")
        self.emitterType.addItem("")
        self.gridLayout_2.addWidget(self.emitterType, 0, 1, 1, 1)
        self.rateLabel = QtGui.QLabel(basicEmitterWidget)
        self.rateLabel.setObjectName("rateLabel")
        self.gridLayout_2.addWidget(self.rateLabel, 1, 0, 1, 1)
        self.rate = QtGui.QDoubleSpinBox(basicEmitterWidget)
        self.rate.setDecimals(2)
        self.rate.setMaximum(1000000000.0)
        self.rate.setProperty("value", 100.0)
        self.rate.setObjectName("rate")
        self.gridLayout_2.addWidget(self.rate, 1, 1, 1, 1)
        self.scaleRateSpeed = QtGui.QCheckBox(basicEmitterWidget)
        self.scaleRateSpeed.setObjectName("scaleRateSpeed")
        self.gridLayout_2.addWidget(self.scaleRateSpeed, 2, 0, 1, 2)
        self.scaleRateObjectSize = QtGui.QCheckBox(basicEmitterWidget)
        self.scaleRateObjectSize.setObjectName("scaleRateObjectSize")
        self.gridLayout_2.addWidget(self.scaleRateObjectSize, 3, 0, 1, 2)
        self.volumeEmitAttr = QtGui.QStackedWidget(basicEmitterWidget)
        self.volumeEmitAttr.setObjectName("volumeEmitAttr")
        self.page = QtGui.QWidget()
        self.page.setObjectName("page")
        self.volumeEmitAttr.addWidget(self.page)
        self.volEmitAttrPage = QtGui.QWidget()
        self.volEmitAttrPage.setObjectName("volEmitAttrPage")
        self.gridLayout = QtGui.QGridLayout(self.volEmitAttrPage)
        self.gridLayout.setObjectName("gridLayout")
        self.volEmitAttrLabel = QtGui.QLabel(self.volEmitAttrPage)
        self.volEmitAttrLabel.setFrameShape(QtGui.QFrame.Panel)
        self.volEmitAttrLabel.setFrameShadow(QtGui.QFrame.Raised)
        self.volEmitAttrLabel.setObjectName("volEmitAttrLabel")
        self.gridLayout.addWidget(self.volEmitAttrLabel, 0, 0, 1, 2)
        self.line = QtGui.QFrame(self.volEmitAttrPage)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 1, 0, 1, 2)
        self.volumeShapeLabel = QtGui.QLabel(self.volEmitAttrPage)
        self.volumeShapeLabel.setObjectName("volumeShapeLabel")
        self.gridLayout.addWidget(self.volumeShapeLabel, 2, 0, 1, 1)
        self.volumeShape = QtGui.QComboBox(self.volEmitAttrPage)
        self.volumeShape.setObjectName("volumeShape")
        self.volumeShape.addItem("")
        self.volumeShape.addItem("")
        self.volumeShape.addItem("")
        self.volumeShape.addItem("")
        self.volumeShape.addItem("")
        self.gridLayout.addWidget(self.volumeShape, 2, 1, 1, 1)
        self.volumeOffsetLabel = QtGui.QLabel(self.volEmitAttrPage)
        self.volumeOffsetLabel.setObjectName("volumeOffsetLabel")
        self.gridLayout.addWidget(self.volumeOffsetLabel, 3, 0, 1, 1)
        self.volumeOffset = QtGui.QDoubleSpinBox(self.volEmitAttrPage)
        self.volumeOffset.setObjectName("volumeOffset")
        self.gridLayout.addWidget(self.volumeOffset, 3, 1, 1, 1)
        self.volumeSweepLabel = QtGui.QLabel(self.volEmitAttrPage)
        self.volumeSweepLabel.setObjectName("volumeSweepLabel")
        self.gridLayout.addWidget(self.volumeSweepLabel, 4, 0, 1, 1)
        self.volumeSweep = QtGui.QDoubleSpinBox(self.volEmitAttrPage)
        self.volumeSweep.setDecimals(3)
        self.volumeSweep.setMaximum(360.0)
        self.volumeSweep.setObjectName("volumeSweep")
        self.gridLayout.addWidget(self.volumeSweep, 4, 1, 2, 1)
        self.sectionRadiusLabel = QtGui.QLabel(self.volEmitAttrPage)
        self.sectionRadiusLabel.setObjectName("sectionRadiusLabel")
        self.gridLayout.addWidget(self.sectionRadiusLabel, 5, 0, 2, 1)
        self.sectionRadius = QtGui.QDoubleSpinBox(self.volEmitAttrPage)
        self.sectionRadius.setDecimals(3)
        self.sectionRadius.setMaximum(1.0)
        self.sectionRadius.setSingleStep(0.1)
        self.sectionRadius.setObjectName("sectionRadius")
        self.gridLayout.addWidget(self.sectionRadius, 6, 1, 1, 1)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 7, 0, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 4, 2, 1, 1)
        self.volumeEmitAttr.addWidget(self.volEmitAttrPage)
        self.gridLayout_2.addWidget(self.volumeEmitAttr, 4, 0, 1, 2)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem2, 1, 2, 1, 1)
        spacerItem3 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem3, 5, 0, 1, 1)

        self.retranslateUi(basicEmitterWidget)
        self.volumeEmitAttr.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(basicEmitterWidget)

    def retranslateUi(self, basicEmitterWidget):
        basicEmitterWidget.setWindowTitle(QtGui.QApplication.translate("basicEmitterWidget", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.emitterTypeLabel.setText(QtGui.QApplication.translate("basicEmitterWidget", "Emitter Type:", None, QtGui.QApplication.UnicodeUTF8))
        self.emitterType.setItemText(0, QtGui.QApplication.translate("basicEmitterWidget", "Directional", None, QtGui.QApplication.UnicodeUTF8))
        self.emitterType.setItemText(1, QtGui.QApplication.translate("basicEmitterWidget", "Omni", None, QtGui.QApplication.UnicodeUTF8))
        self.emitterType.setItemText(2, QtGui.QApplication.translate("basicEmitterWidget", "Surface", None, QtGui.QApplication.UnicodeUTF8))
        self.emitterType.setItemText(3, QtGui.QApplication.translate("basicEmitterWidget", "Curve", None, QtGui.QApplication.UnicodeUTF8))
        self.emitterType.setItemText(4, QtGui.QApplication.translate("basicEmitterWidget", "Volume", None, QtGui.QApplication.UnicodeUTF8))
        self.rateLabel.setText(QtGui.QApplication.translate("basicEmitterWidget", "Rate (Particles/Sec):", None, QtGui.QApplication.UnicodeUTF8))
        self.scaleRateSpeed.setText(QtGui.QApplication.translate("basicEmitterWidget", "Scale Rate by Speed", None, QtGui.QApplication.UnicodeUTF8))
        self.scaleRateObjectSize.setText(QtGui.QApplication.translate("basicEmitterWidget", "Scale Rate By Object Size", None, QtGui.QApplication.UnicodeUTF8))
        self.volEmitAttrLabel.setText(QtGui.QApplication.translate("basicEmitterWidget", "Volume Emitter Attributes", None, QtGui.QApplication.UnicodeUTF8))
        self.volumeShapeLabel.setText(QtGui.QApplication.translate("basicEmitterWidget", "Volume Shape", None, QtGui.QApplication.UnicodeUTF8))
        self.volumeShape.setItemText(0, QtGui.QApplication.translate("basicEmitterWidget", "Cube", None, QtGui.QApplication.UnicodeUTF8))
        self.volumeShape.setItemText(1, QtGui.QApplication.translate("basicEmitterWidget", "Sphere", None, QtGui.QApplication.UnicodeUTF8))
        self.volumeShape.setItemText(2, QtGui.QApplication.translate("basicEmitterWidget", "Cylinder", None, QtGui.QApplication.UnicodeUTF8))
        self.volumeShape.setItemText(3, QtGui.QApplication.translate("basicEmitterWidget", "Cone", None, QtGui.QApplication.UnicodeUTF8))
        self.volumeShape.setItemText(4, QtGui.QApplication.translate("basicEmitterWidget", "Torus", None, QtGui.QApplication.UnicodeUTF8))
        self.volumeOffsetLabel.setText(QtGui.QApplication.translate("basicEmitterWidget", "Volume Offset", None, QtGui.QApplication.UnicodeUTF8))
        self.volumeSweepLabel.setText(QtGui.QApplication.translate("basicEmitterWidget", "Volume Sweep", None, QtGui.QApplication.UnicodeUTF8))
        self.sectionRadiusLabel.setText(QtGui.QApplication.translate("basicEmitterWidget", "Section Radius", None, QtGui.QApplication.UnicodeUTF8))

