# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'collisionEvent.ui'
#
# Created: Mon Mar 19 20:23:30 2012
#      by: PyQt4 UI code generator 4.7.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_collisionEvent(object):
    def setupUi(self, collisionEvent):
        collisionEvent.setObjectName("collisionEvent")
        collisionEvent.resize(562, 536)
        collisionEvent.setStatusTip("")
        collisionEvent.setWhatsThis("")
        self.gridLayout = QtGui.QGridLayout(collisionEvent)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtGui.QLabel(collisionEvent)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 3)
        self.eventIsAffecting = QtGui.QLineEdit(collisionEvent)
        self.eventIsAffecting.setReadOnly(True)
        self.eventIsAffecting.setObjectName("eventIsAffecting")
        self.gridLayout.addWidget(self.eventIsAffecting, 1, 0, 1, 3)
        self.label_2 = QtGui.QLabel(collisionEvent)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 0, 1, 2)
        self.eventName = QtGui.QLineEdit(collisionEvent)
        self.eventName.setReadOnly(True)
        self.eventName.setObjectName("eventName")
        self.gridLayout.addWidget(self.eventName, 3, 0, 1, 3)
        self.line = QtGui.QFrame(collisionEvent)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 4, 0, 1, 4)
        self.label_3 = QtGui.QLabel(collisionEvent)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 5, 0, 1, 4)
        self.allCollisions = QtGui.QCheckBox(collisionEvent)
        self.allCollisions.setChecked(True)
        self.allCollisions.setObjectName("allCollisions")
        self.gridLayout.addWidget(self.allCollisions, 6, 0, 1, 4)
        self.line_2 = QtGui.QFrame(collisionEvent)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout.addWidget(self.line_2, 8, 0, 1, 4)
        self.label_5 = QtGui.QLabel(collisionEvent)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 9, 0, 1, 4)
        self.label_6 = QtGui.QLabel(collisionEvent)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 10, 0, 1, 1)
        self.emitRandomParticles = QtGui.QCheckBox(collisionEvent)
        self.emitRandomParticles.setObjectName("emitRandomParticles")
        self.gridLayout.addWidget(self.emitRandomParticles, 11, 0, 1, 4)
        self.label_7 = QtGui.QLabel(collisionEvent)
        self.label_7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 13, 0, 1, 1)
        self.label_8 = QtGui.QLabel(collisionEvent)
        self.label_8.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 14, 0, 1, 1)
        self.label_10 = QtGui.QLabel(collisionEvent)
        self.label_10.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 15, 0, 1, 1)
        self.line_3 = QtGui.QFrame(collisionEvent)
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.gridLayout.addWidget(self.line_3, 16, 0, 1, 4)
        self.label_9 = QtGui.QLabel(collisionEvent)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 17, 0, 1, 4)
        self.targetParticleSystem = QtGui.QLineEdit(collisionEvent)
        self.targetParticleSystem.setWhatsThis("")
        self.targetParticleSystem.setObjectName("targetParticleSystem")
        self.gridLayout.addWidget(self.targetParticleSystem, 18, 0, 1, 3)
        self.label_4 = QtGui.QLabel(collisionEvent)
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 7, 0, 1, 1)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 15, 4, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem1, 19, 0, 1, 1)
        self.numParticles = QtGui.QSpinBox(collisionEvent)
        self.numParticles.setMaximum(999999999)
        self.numParticles.setProperty("value", 1)
        self.numParticles.setObjectName("numParticles")
        self.gridLayout.addWidget(self.numParticles, 13, 1, 1, 1)
        self.spread = QtGui.QDoubleSpinBox(collisionEvent)
        self.spread.setDecimals(3)
        self.spread.setMaximum(2.0)
        self.spread.setSingleStep(0.01)
        self.spread.setProperty("value", 0.0)
        self.spread.setObjectName("spread")
        self.gridLayout.addWidget(self.spread, 14, 1, 1, 1)
        self.inheritVelocity = QtGui.QDoubleSpinBox(collisionEvent)
        self.inheritVelocity.setDecimals(3)
        self.inheritVelocity.setMaximum(1.0)
        self.inheritVelocity.setSingleStep(0.01)
        self.inheritVelocity.setProperty("value", 0.0)
        self.inheritVelocity.setObjectName("inheritVelocity")
        self.gridLayout.addWidget(self.inheritVelocity, 15, 1, 1, 1)
        self.collisionNumber = QtGui.QSpinBox(collisionEvent)
        self.collisionNumber.setEnabled(False)
        self.collisionNumber.setMinimum(1)
        self.collisionNumber.setMaximum(999999999)
        self.collisionNumber.setProperty("value", 1)
        self.collisionNumber.setObjectName("collisionNumber")
        self.gridLayout.addWidget(self.collisionNumber, 7, 1, 1, 1)
        self.emit = QtGui.QRadioButton(collisionEvent)
        self.emit.setChecked(True)
        self.emit.setObjectName("emit")
        self.gridLayout.addWidget(self.emit, 10, 1, 1, 1)
        self.split = QtGui.QRadioButton(collisionEvent)
        self.split.setChecked(False)
        self.split.setObjectName("split")
        self.gridLayout.addWidget(self.split, 10, 2, 1, 1)
        self.originalParticleDies = QtGui.QCheckBox(collisionEvent)
        self.originalParticleDies.setObjectName("originalParticleDies")
        self.gridLayout.addWidget(self.originalParticleDies, 12, 0, 1, 3)

        self.retranslateUi(collisionEvent)
        QtCore.QObject.connect(self.allCollisions, QtCore.SIGNAL("clicked(bool)"), self.collisionNumber.setDisabled)
        QtCore.QObject.connect(self.split, QtCore.SIGNAL("clicked(bool)"), self.originalParticleDies.setDisabled)
        QtCore.QObject.connect(self.emit, QtCore.SIGNAL("clicked(bool)"), self.originalParticleDies.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(collisionEvent)

    def retranslateUi(self, collisionEvent):
        collisionEvent.setWindowTitle(QtGui.QApplication.translate("collisionEvent", "Form", None, QtGui.QApplication.UnicodeUTF8))
        collisionEvent.setToolTip(QtGui.QApplication.translate("collisionEvent", "Get the particleShape name from a Blue Behavior Node or Orange Look Node", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("collisionEvent", "Event is affecting:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("collisionEvent", "Event Name:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("collisionEvent", "How many times should the collision event happen?", None, QtGui.QApplication.UnicodeUTF8))
        self.allCollisions.setText(QtGui.QApplication.translate("collisionEvent", "Event occurs at all collisions", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("collisionEvent", "When the particles collide, what should they do?", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("collisionEvent", "Type:", None, QtGui.QApplication.UnicodeUTF8))
        self.emitRandomParticles.setText(QtGui.QApplication.translate("collisionEvent", "Emit random particles between 0 and \"Num Particles\"", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("collisionEvent", "Num Particles:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("collisionEvent", "Spread:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("collisionEvent", "Inherit Velocity:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("collisionEvent", "New particles will be from the below particle system:", None, QtGui.QApplication.UnicodeUTF8))
        self.targetParticleSystem.setText(QtGui.QApplication.translate("collisionEvent", "<Replace this with particleShape name>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("collisionEvent", "Collision Number:", None, QtGui.QApplication.UnicodeUTF8))
        self.emit.setText(QtGui.QApplication.translate("collisionEvent", "Emit", None, QtGui.QApplication.UnicodeUTF8))
        self.split.setText(QtGui.QApplication.translate("collisionEvent", "Split", None, QtGui.QApplication.UnicodeUTF8))
        self.originalParticleDies.setText(QtGui.QApplication.translate("collisionEvent", "Original particle dies", None, QtGui.QApplication.UnicodeUTF8))

