# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gravityForce.ui'
#
# Created: Sat Mar 17 16:16:38 2012
#      by: PyQt4 UI code generator 4.7.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_gravityForce(object):
    def setupUi(self, gravityForce):
        gravityForce.setObjectName("gravityForce")
        gravityForce.resize(221, 202)
        self.gridLayout = QtGui.QGridLayout(gravityForce)
        self.gridLayout.setObjectName("gridLayout")
        self.magnitudeLabel = QtGui.QLabel(gravityForce)
        self.magnitudeLabel.setObjectName("magnitudeLabel")
        self.gridLayout.addWidget(self.magnitudeLabel, 0, 0, 1, 1)
        self.attenuationLabel = QtGui.QLabel(gravityForce)
        self.attenuationLabel.setObjectName("attenuationLabel")
        self.gridLayout.addWidget(self.attenuationLabel, 1, 0, 1, 1)
        self.directionLabel = QtGui.QLabel(gravityForce)
        self.directionLabel.setObjectName("directionLabel")
        self.gridLayout.addWidget(self.directionLabel, 2, 0, 1, 2)
        self.directionX = QtGui.QDoubleSpinBox(gravityForce)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.directionX.sizePolicy().hasHeightForWidth())
        self.directionX.setSizePolicy(sizePolicy)
        self.directionX.setMinimum(-999999999.0)
        self.directionX.setMaximum(999999999.0)
        self.directionX.setSingleStep(0.01)
        self.directionX.setProperty("value", 0.0)
        self.directionX.setObjectName("directionX")
        self.gridLayout.addWidget(self.directionX, 3, 0, 1, 1)
        self.directionY = QtGui.QDoubleSpinBox(gravityForce)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.directionY.sizePolicy().hasHeightForWidth())
        self.directionY.setSizePolicy(sizePolicy)
        self.directionY.setMinimum(-999999999.0)
        self.directionY.setMaximum(999999999.0)
        self.directionY.setSingleStep(0.01)
        self.directionY.setProperty("value", -1.0)
        self.directionY.setObjectName("directionY")
        self.gridLayout.addWidget(self.directionY, 3, 1, 1, 2)
        self.directionZ = QtGui.QDoubleSpinBox(gravityForce)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.directionZ.sizePolicy().hasHeightForWidth())
        self.directionZ.setSizePolicy(sizePolicy)
        self.directionZ.setMinimum(-999999999.0)
        self.directionZ.setMaximum(999999999.0)
        self.directionZ.setSingleStep(0.01)
        self.directionZ.setProperty("value", 0.0)
        self.directionZ.setObjectName("directionZ")
        self.gridLayout.addWidget(self.directionZ, 3, 4, 1, 1)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 1, 5, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem1, 4, 1, 1, 1)
        self.magnitude = QtGui.QDoubleSpinBox(gravityForce)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.magnitude.sizePolicy().hasHeightForWidth())
        self.magnitude.setSizePolicy(sizePolicy)
        self.magnitude.setMinimum(-999999999.0)
        self.magnitude.setMaximum(999999999.0)
        self.magnitude.setProperty("value", 9.8)
        self.magnitude.setObjectName("magnitude")
        self.gridLayout.addWidget(self.magnitude, 0, 1, 1, 1)
        self.attenuation = QtGui.QDoubleSpinBox(gravityForce)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.attenuation.sizePolicy().hasHeightForWidth())
        self.attenuation.setSizePolicy(sizePolicy)
        self.attenuation.setObjectName("attenuation")
        self.gridLayout.addWidget(self.attenuation, 1, 1, 1, 1)

        self.retranslateUi(gravityForce)
        QtCore.QMetaObject.connectSlotsByName(gravityForce)

    def retranslateUi(self, gravityForce):
        gravityForce.setWindowTitle(QtGui.QApplication.translate("gravityForce", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.magnitudeLabel.setText(QtGui.QApplication.translate("gravityForce", "Magnitude", None, QtGui.QApplication.UnicodeUTF8))
        self.attenuationLabel.setText(QtGui.QApplication.translate("gravityForce", "Attenuation", None, QtGui.QApplication.UnicodeUTF8))
        self.directionLabel.setText(QtGui.QApplication.translate("gravityForce", "Direction:", None, QtGui.QApplication.UnicodeUTF8))

