# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'instancer.ui'
#
# Created: Mon Mar 12 14:16:45 2012
#      by: PyQt4 UI code generator 4.7.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_instancer(object):
    def setupUi(self, instancer):
        instancer.setObjectName("instancer")
        instancer.resize(400, 494)
        self.gridLayout = QtGui.QGridLayout(instancer)
        self.gridLayout.setObjectName("gridLayout")
        self.rotAngleUnitsLabel = QtGui.QLabel(instancer)
        self.rotAngleUnitsLabel.setObjectName("rotAngleUnitsLabel")
        self.gridLayout.addWidget(self.rotAngleUnitsLabel, 0, 0, 1, 2)
        self.rotationAngleUnits = QtGui.QComboBox(instancer)
        self.rotationAngleUnits.setObjectName("rotationAngleUnits")
        self.rotationAngleUnits.addItem("")
        self.rotationAngleUnits.addItem("")
        self.gridLayout.addWidget(self.rotationAngleUnits, 0, 2, 1, 1)
        self.lodLabel = QtGui.QLabel(instancer)
        self.lodLabel.setObjectName("lodLabel")
        self.gridLayout.addWidget(self.lodLabel, 1, 0, 1, 1)
        self.levelOfDetail = QtGui.QComboBox(instancer)
        self.levelOfDetail.setObjectName("levelOfDetail")
        self.levelOfDetail.addItem("")
        self.levelOfDetail.addItem("")
        self.levelOfDetail.addItem("")
        self.gridLayout.addWidget(self.levelOfDetail, 1, 2, 1, 1)
        self.cycleLabel = QtGui.QLabel(instancer)
        self.cycleLabel.setObjectName("cycleLabel")
        self.gridLayout.addWidget(self.cycleLabel, 2, 0, 1, 1)
        self.cycle = QtGui.QComboBox(instancer)
        self.cycle.setObjectName("cycle")
        self.cycle.addItem("")
        self.cycle.addItem("")
        self.gridLayout.addWidget(self.cycle, 2, 2, 1, 1)
        self.cycleStepUnitLabel = QtGui.QLabel(instancer)
        self.cycleStepUnitLabel.setObjectName("cycleStepUnitLabel")
        self.gridLayout.addWidget(self.cycleStepUnitLabel, 3, 0, 1, 1)
        self.cycleStepUnit = QtGui.QComboBox(instancer)
        self.cycleStepUnit.setObjectName("cycleStepUnit")
        self.cycleStepUnit.addItem("")
        self.cycleStepUnit.addItem("")
        self.gridLayout.addWidget(self.cycleStepUnit, 3, 2, 1, 1)
        self.cycleStepLabel = QtGui.QLabel(instancer)
        self.cycleStepLabel.setObjectName("cycleStepLabel")
        self.gridLayout.addWidget(self.cycleStepLabel, 4, 0, 1, 1)
        self.cycleStep = QtGui.QDoubleSpinBox(instancer)
        self.cycleStep.setDecimals(3)
        self.cycleStep.setMinimum(1.0)
        self.cycleStep.setMaximum(1000000000.0)
        self.cycleStep.setProperty("value", 1.0)
        self.cycleStep.setObjectName("cycleStep")
        self.gridLayout.addWidget(self.cycleStep, 4, 2, 1, 1)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 4, 3, 1, 1)
        self.instancedObjectsLabel = QtGui.QLabel(instancer)
        self.instancedObjectsLabel.setObjectName("instancedObjectsLabel")
        self.gridLayout.addWidget(self.instancedObjectsLabel, 5, 0, 1, 2)
        self.instancedObjects = QtGui.QListWidget(instancer)
        self.instancedObjects.setFrameShape(QtGui.QFrame.Box)
        self.instancedObjects.setFrameShadow(QtGui.QFrame.Sunken)
        self.instancedObjects.setProperty("isWrapping", True)
        self.instancedObjects.setObjectName("instancedObjects")
        self.gridLayout.addWidget(self.instancedObjects, 6, 0, 1, 3)
        self.instancerNameLabel1 = QtGui.QLabel(instancer)
        self.instancerNameLabel1.setObjectName("instancerNameLabel1")
        self.gridLayout.addWidget(self.instancerNameLabel1, 7, 0, 1, 1)
        self.instancerNameLabel = QtGui.QLineEdit(instancer)
        self.instancerNameLabel.setReadOnly(True)
        self.instancerNameLabel.setObjectName("instancerNameLabel")
        self.gridLayout.addWidget(self.instancerNameLabel, 7, 1, 1, 2)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem1, 8, 0, 1, 1)

        self.retranslateUi(instancer)
        QtCore.QMetaObject.connectSlotsByName(instancer)

    def retranslateUi(self, instancer):
        instancer.setWindowTitle(QtGui.QApplication.translate("instancer", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.rotAngleUnitsLabel.setText(QtGui.QApplication.translate("instancer", "Rotation Angle Units", None, QtGui.QApplication.UnicodeUTF8))
        self.rotationAngleUnits.setItemText(0, QtGui.QApplication.translate("instancer", "Degrees", None, QtGui.QApplication.UnicodeUTF8))
        self.rotationAngleUnits.setItemText(1, QtGui.QApplication.translate("instancer", "Radians", None, QtGui.QApplication.UnicodeUTF8))
        self.lodLabel.setText(QtGui.QApplication.translate("instancer", "Level Of Detail", None, QtGui.QApplication.UnicodeUTF8))
        self.levelOfDetail.setItemText(0, QtGui.QApplication.translate("instancer", "Geometry", None, QtGui.QApplication.UnicodeUTF8))
        self.levelOfDetail.setItemText(1, QtGui.QApplication.translate("instancer", "BoundingBoxes", None, QtGui.QApplication.UnicodeUTF8))
        self.levelOfDetail.setItemText(2, QtGui.QApplication.translate("instancer", "BoundingBox", None, QtGui.QApplication.UnicodeUTF8))
        self.cycleLabel.setText(QtGui.QApplication.translate("instancer", "Cycle", None, QtGui.QApplication.UnicodeUTF8))
        self.cycle.setItemText(0, QtGui.QApplication.translate("instancer", "None", None, QtGui.QApplication.UnicodeUTF8))
        self.cycle.setItemText(1, QtGui.QApplication.translate("instancer", "Sequential", None, QtGui.QApplication.UnicodeUTF8))
        self.cycleStepUnitLabel.setText(QtGui.QApplication.translate("instancer", "Cycle Step Unit", None, QtGui.QApplication.UnicodeUTF8))
        self.cycleStepUnit.setItemText(0, QtGui.QApplication.translate("instancer", "Frames", None, QtGui.QApplication.UnicodeUTF8))
        self.cycleStepUnit.setItemText(1, QtGui.QApplication.translate("instancer", "Seconds", None, QtGui.QApplication.UnicodeUTF8))
        self.cycleStepLabel.setText(QtGui.QApplication.translate("instancer", "Cycle Step", None, QtGui.QApplication.UnicodeUTF8))
        self.instancedObjectsLabel.setText(QtGui.QApplication.translate("instancer", "Instanced Objects:", None, QtGui.QApplication.UnicodeUTF8))
        self.instancerNameLabel1.setText(QtGui.QApplication.translate("instancer", "Instancer Name:", None, QtGui.QApplication.UnicodeUTF8))

