# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'perParticleAttr.ui'
#
# Created: Sat Mar 10 19:23:03 2012
#      by: PyQt4 UI code generator 4.7.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_perParticleAttr(object):
    def setupUi(self, perParticleAttr):
        perParticleAttr.setObjectName("perParticleAttr")
        perParticleAttr.resize(414, 601)
        self.gridLayout = QtGui.QGridLayout(perParticleAttr)
        self.gridLayout.setObjectName("gridLayout")
        self.evaluteExpressionLabel = QtGui.QLabel(perParticleAttr)
        self.evaluteExpressionLabel.setObjectName("evaluteExpressionLabel")
        self.gridLayout.addWidget(self.evaluteExpressionLabel, 0, 0, 1, 1)
        self.runExpression = QtGui.QComboBox(perParticleAttr)
        self.runExpression.setObjectName("runExpression")
        self.runExpression.addItem("")
        self.runExpression.addItem("")
        self.runExpression.addItem("")
        self.gridLayout.addWidget(self.runExpression, 1, 0, 1, 1)
        self.expressionLabel = QtGui.QLabel(perParticleAttr)
        self.expressionLabel.setObjectName("expressionLabel")
        self.gridLayout.addWidget(self.expressionLabel, 2, 0, 1, 1)
        self.particleAttrExpressions = QtGui.QStackedWidget(perParticleAttr)
        self.particleAttrExpressions.setObjectName("particleAttrExpressions")
        self.creationExpPage = QtGui.QWidget()
        self.creationExpPage.setObjectName("creationExpPage")
        self.verticalLayout = QtGui.QVBoxLayout(self.creationExpPage)
        self.verticalLayout.setObjectName("verticalLayout")
        self.particleAttrExpressions.addWidget(self.creationExpPage)
        self.gridLayout.addWidget(self.particleAttrExpressions, 3, 0, 1, 1)
        self.partAttrLabel = QtGui.QLabel(perParticleAttr)
        self.partAttrLabel.setObjectName("partAttrLabel")
        self.gridLayout.addWidget(self.partAttrLabel, 5, 0, 1, 1)
        spacerItem = QtGui.QSpacerItem(100, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 7, 1, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem1, 13, 0, 1, 1)
        self.updateExpressionButton = QtGui.QPushButton(perParticleAttr)
        self.updateExpressionButton.setObjectName("updateExpressionButton")
        self.gridLayout.addWidget(self.updateExpressionButton, 12, 0, 1, 1)
        self.attrList = QtGui.QListWidget(perParticleAttr)
        self.attrList.setDragEnabled(True)
        self.attrList.setDragDropMode(QtGui.QAbstractItemView.DragOnly)
        self.attrList.setObjectName("attrList")
        QtGui.QListWidgetItem(self.attrList)
        QtGui.QListWidgetItem(self.attrList)
        QtGui.QListWidgetItem(self.attrList)
        QtGui.QListWidgetItem(self.attrList)
        QtGui.QListWidgetItem(self.attrList)
        QtGui.QListWidgetItem(self.attrList)
        QtGui.QListWidgetItem(self.attrList)
        self.gridLayout.addWidget(self.attrList, 6, 0, 1, 1)
        self.currentParticleShapeLabel = QtGui.QLabel(perParticleAttr)
        self.currentParticleShapeLabel.setObjectName("currentParticleShapeLabel")
        self.gridLayout.addWidget(self.currentParticleShapeLabel, 7, 0, 1, 1)
        self.currentParticleShape = QtGui.QLineEdit(perParticleAttr)
        self.currentParticleShape.setDragEnabled(True)
        self.currentParticleShape.setReadOnly(True)
        self.currentParticleShape.setObjectName("currentParticleShape")
        self.gridLayout.addWidget(self.currentParticleShape, 8, 0, 1, 1)

        self.retranslateUi(perParticleAttr)
        self.particleAttrExpressions.setCurrentIndex(0)
        QtCore.QObject.connect(self.runExpression, QtCore.SIGNAL("activated(int)"), self.particleAttrExpressions.setCurrentIndex)
        QtCore.QMetaObject.connectSlotsByName(perParticleAttr)

    def retranslateUi(self, perParticleAttr):
        perParticleAttr.setWindowTitle(QtGui.QApplication.translate("perParticleAttr", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.evaluteExpressionLabel.setText(QtGui.QApplication.translate("perParticleAttr", "Evaluate expression:", None, QtGui.QApplication.UnicodeUTF8))
        self.runExpression.setItemText(0, QtGui.QApplication.translate("perParticleAttr", "At Creation", None, QtGui.QApplication.UnicodeUTF8))
        self.runExpression.setItemText(1, QtGui.QApplication.translate("perParticleAttr", "Before Dynamics", None, QtGui.QApplication.UnicodeUTF8))
        self.runExpression.setItemText(2, QtGui.QApplication.translate("perParticleAttr", "After Dynamics", None, QtGui.QApplication.UnicodeUTF8))
        self.expressionLabel.setText(QtGui.QApplication.translate("perParticleAttr", "Expression:", None, QtGui.QApplication.UnicodeUTF8))
        self.partAttrLabel.setText(QtGui.QApplication.translate("perParticleAttr", "Particle Attributes:", None, QtGui.QApplication.UnicodeUTF8))
        self.updateExpressionButton.setText(QtGui.QApplication.translate("perParticleAttr", "Update Expression", None, QtGui.QApplication.UnicodeUTF8))
        __sortingEnabled = self.attrList.isSortingEnabled()
        self.attrList.setSortingEnabled(False)
        self.attrList.item(0).setText(QtGui.QApplication.translate("perParticleAttr", "position", None, QtGui.QApplication.UnicodeUTF8))
        self.attrList.item(1).setText(QtGui.QApplication.translate("perParticleAttr", "velocity", None, QtGui.QApplication.UnicodeUTF8))
        self.attrList.item(2).setText(QtGui.QApplication.translate("perParticleAttr", "acceleration", None, QtGui.QApplication.UnicodeUTF8))
        self.attrList.item(3).setText(QtGui.QApplication.translate("perParticleAttr", "mass", None, QtGui.QApplication.UnicodeUTF8))
        self.attrList.item(4).setText(QtGui.QApplication.translate("perParticleAttr", "opacityPP", None, QtGui.QApplication.UnicodeUTF8))
        self.attrList.item(5).setText(QtGui.QApplication.translate("perParticleAttr", "lifespanPP", None, QtGui.QApplication.UnicodeUTF8))
        self.attrList.item(6).setText(QtGui.QApplication.translate("perParticleAttr", "rgbPP", None, QtGui.QApplication.UnicodeUTF8))
        self.attrList.setSortingEnabled(__sortingEnabled)
        self.currentParticleShapeLabel.setText(QtGui.QApplication.translate("perParticleAttr", "ParticleShape: ", None, QtGui.QApplication.UnicodeUTF8))
        self.currentParticleShape.setText(QtGui.QApplication.translate("perParticleAttr", "None", None, QtGui.QApplication.UnicodeUTF8))

