# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'turbulenceForce.ui'
#
# Created: Sat Mar 17 17:02:37 2012
#      by: PyQt4 UI code generator 4.7.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_turbulenceForce(object):
    def setupUi(self, turbulenceForce):
        turbulenceForce.setObjectName("turbulenceForce")
        turbulenceForce.resize(267, 378)
        self.gridLayout = QtGui.QGridLayout(turbulenceForce)
        self.gridLayout.setObjectName("gridLayout")
        self.magnitudeLabel = QtGui.QLabel(turbulenceForce)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.magnitudeLabel.sizePolicy().hasHeightForWidth())
        self.magnitudeLabel.setSizePolicy(sizePolicy)
        self.magnitudeLabel.setObjectName("magnitudeLabel")
        self.gridLayout.addWidget(self.magnitudeLabel, 0, 0, 1, 1)
        self.magnitude = QtGui.QDoubleSpinBox(turbulenceForce)
        self.magnitude.setMinimum(-999999999.0)
        self.magnitude.setMaximum(999999999.0)
        self.magnitude.setProperty("value", 5.0)
        self.magnitude.setObjectName("magnitude")
        self.gridLayout.addWidget(self.magnitude, 0, 1, 1, 1)
        self.attenuationLabel = QtGui.QLabel(turbulenceForce)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.attenuationLabel.sizePolicy().hasHeightForWidth())
        self.attenuationLabel.setSizePolicy(sizePolicy)
        self.attenuationLabel.setObjectName("attenuationLabel")
        self.gridLayout.addWidget(self.attenuationLabel, 1, 0, 1, 1)
        self.attenuation = QtGui.QDoubleSpinBox(turbulenceForce)
        self.attenuation.setMinimum(-999999999.0)
        self.attenuation.setMaximum(999999999.0)
        self.attenuation.setProperty("value", 1.0)
        self.attenuation.setObjectName("attenuation")
        self.gridLayout.addWidget(self.attenuation, 1, 1, 1, 1)
        self.frequency = QtGui.QDoubleSpinBox(turbulenceForce)
        self.frequency.setMinimum(-999999999.0)
        self.frequency.setMaximum(999999999.0)
        self.frequency.setProperty("value", 1.0)
        self.frequency.setObjectName("frequency")
        self.gridLayout.addWidget(self.frequency, 2, 1, 1, 1)
        self.phaseXLabel = QtGui.QLabel(turbulenceForce)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.phaseXLabel.sizePolicy().hasHeightForWidth())
        self.phaseXLabel.setSizePolicy(sizePolicy)
        self.phaseXLabel.setObjectName("phaseXLabel")
        self.gridLayout.addWidget(self.phaseXLabel, 3, 0, 1, 1)
        self.phaseX = QtGui.QDoubleSpinBox(turbulenceForce)
        self.phaseX.setMinimum(-999999999.0)
        self.phaseX.setMaximum(999999999.0)
        self.phaseX.setObjectName("phaseX")
        self.gridLayout.addWidget(self.phaseX, 3, 1, 1, 1)
        self.phaseYLabel = QtGui.QLabel(turbulenceForce)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.phaseYLabel.sizePolicy().hasHeightForWidth())
        self.phaseYLabel.setSizePolicy(sizePolicy)
        self.phaseYLabel.setObjectName("phaseYLabel")
        self.gridLayout.addWidget(self.phaseYLabel, 4, 0, 1, 1)
        self.phaseY = QtGui.QDoubleSpinBox(turbulenceForce)
        self.phaseY.setMinimum(-999999999.0)
        self.phaseY.setMaximum(999999999.0)
        self.phaseY.setObjectName("phaseY")
        self.gridLayout.addWidget(self.phaseY, 4, 1, 1, 1)
        self.phaseZLabel = QtGui.QLabel(turbulenceForce)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.phaseZLabel.sizePolicy().hasHeightForWidth())
        self.phaseZLabel.setSizePolicy(sizePolicy)
        self.phaseZLabel.setObjectName("phaseZLabel")
        self.gridLayout.addWidget(self.phaseZLabel, 5, 0, 1, 1)
        self.phaseZ = QtGui.QDoubleSpinBox(turbulenceForce)
        self.phaseZ.setMinimum(-999999999.0)
        self.phaseZ.setMaximum(999999999.0)
        self.phaseZ.setObjectName("phaseZ")
        self.gridLayout.addWidget(self.phaseZ, 5, 1, 1, 1)
        self.interpolationTypeLabel = QtGui.QLabel(turbulenceForce)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.interpolationTypeLabel.sizePolicy().hasHeightForWidth())
        self.interpolationTypeLabel.setSizePolicy(sizePolicy)
        self.interpolationTypeLabel.setObjectName("interpolationTypeLabel")
        self.gridLayout.addWidget(self.interpolationTypeLabel, 6, 0, 1, 1)
        self.interpolationType = QtGui.QComboBox(turbulenceForce)
        self.interpolationType.setObjectName("interpolationType")
        self.interpolationType.addItem("")
        self.interpolationType.addItem("")
        self.gridLayout.addWidget(self.interpolationType, 6, 1, 1, 1)
        self.noiseLevelLabel = QtGui.QLabel(turbulenceForce)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.noiseLevelLabel.sizePolicy().hasHeightForWidth())
        self.noiseLevelLabel.setSizePolicy(sizePolicy)
        self.noiseLevelLabel.setObjectName("noiseLevelLabel")
        self.gridLayout.addWidget(self.noiseLevelLabel, 7, 0, 1, 1)
        self.noiseLevel = QtGui.QSpinBox(turbulenceForce)
        self.noiseLevel.setObjectName("noiseLevel")
        self.gridLayout.addWidget(self.noiseLevel, 7, 1, 1, 1)
        self.noiseRatioLabel = QtGui.QLabel(turbulenceForce)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.noiseRatioLabel.sizePolicy().hasHeightForWidth())
        self.noiseRatioLabel.setSizePolicy(sizePolicy)
        self.noiseRatioLabel.setObjectName("noiseRatioLabel")
        self.gridLayout.addWidget(self.noiseRatioLabel, 8, 0, 1, 1)
        self.noiseRatio = QtGui.QDoubleSpinBox(turbulenceForce)
        self.noiseRatio.setMinimum(-999999999.0)
        self.noiseRatio.setMaximum(999999999.0)
        self.noiseRatio.setSingleStep(0.1)
        self.noiseRatio.setProperty("value", 0.71)
        self.noiseRatio.setObjectName("noiseRatio")
        self.gridLayout.addWidget(self.noiseRatio, 8, 1, 1, 1)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 3, 2, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem1, 9, 0, 1, 1)
        self.frequencyLabel = QtGui.QLabel(turbulenceForce)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frequencyLabel.sizePolicy().hasHeightForWidth())
        self.frequencyLabel.setSizePolicy(sizePolicy)
        self.frequencyLabel.setObjectName("frequencyLabel")
        self.gridLayout.addWidget(self.frequencyLabel, 2, 0, 1, 1)

        self.retranslateUi(turbulenceForce)
        QtCore.QMetaObject.connectSlotsByName(turbulenceForce)

    def retranslateUi(self, turbulenceForce):
        turbulenceForce.setWindowTitle(QtGui.QApplication.translate("turbulenceForce", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.magnitudeLabel.setText(QtGui.QApplication.translate("turbulenceForce", "Magnitude", None, QtGui.QApplication.UnicodeUTF8))
        self.attenuationLabel.setText(QtGui.QApplication.translate("turbulenceForce", "Attenuation", None, QtGui.QApplication.UnicodeUTF8))
        self.phaseXLabel.setText(QtGui.QApplication.translate("turbulenceForce", "Phase X", None, QtGui.QApplication.UnicodeUTF8))
        self.phaseYLabel.setText(QtGui.QApplication.translate("turbulenceForce", "Phase Y", None, QtGui.QApplication.UnicodeUTF8))
        self.phaseZLabel.setText(QtGui.QApplication.translate("turbulenceForce", "Phase Z", None, QtGui.QApplication.UnicodeUTF8))
        self.interpolationTypeLabel.setText(QtGui.QApplication.translate("turbulenceForce", "Interpolation Type", None, QtGui.QApplication.UnicodeUTF8))
        self.interpolationType.setItemText(0, QtGui.QApplication.translate("turbulenceForce", "Linear", None, QtGui.QApplication.UnicodeUTF8))
        self.interpolationType.setItemText(1, QtGui.QApplication.translate("turbulenceForce", "Quadratic", None, QtGui.QApplication.UnicodeUTF8))
        self.noiseLevelLabel.setText(QtGui.QApplication.translate("turbulenceForce", "Noise Level", None, QtGui.QApplication.UnicodeUTF8))
        self.noiseRatioLabel.setText(QtGui.QApplication.translate("turbulenceForce", "Noise Ratio", None, QtGui.QApplication.UnicodeUTF8))
        self.frequencyLabel.setText(QtGui.QApplication.translate("turbulenceForce", "Frequency", None, QtGui.QApplication.UnicodeUTF8))

