# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'volSpeedAttr.ui'
#
# Created: Fri Mar 09 19:20:07 2012
#      by: PyQt4 UI code generator 4.7.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_volSpeedAttr(object):
    def setupUi(self, volSpeedAttr):
        volSpeedAttr.setObjectName("volSpeedAttr")
        volSpeedAttr.resize(251, 300)
        self.gridLayout = QtGui.QGridLayout(volSpeedAttr)
        self.gridLayout.setObjectName("gridLayout")
        self.awayFromCenterLabel = QtGui.QLabel(volSpeedAttr)
        self.awayFromCenterLabel.setObjectName("awayFromCenterLabel")
        self.gridLayout.addWidget(self.awayFromCenterLabel, 0, 0, 1, 1)
        self.awayFromCenter = QtGui.QDoubleSpinBox(volSpeedAttr)
        self.awayFromCenter.setDecimals(3)
        self.awayFromCenter.setMinimum(-1000000000.0)
        self.awayFromCenter.setMaximum(1000000000.0)
        self.awayFromCenter.setProperty("value", 1.0)
        self.awayFromCenter.setObjectName("awayFromCenter")
        self.gridLayout.addWidget(self.awayFromCenter, 0, 2, 1, 1)
        self.awayFromAxisLabel = QtGui.QLabel(volSpeedAttr)
        self.awayFromAxisLabel.setObjectName("awayFromAxisLabel")
        self.gridLayout.addWidget(self.awayFromAxisLabel, 1, 0, 1, 1)
        self.alongAxisLabel = QtGui.QLabel(volSpeedAttr)
        self.alongAxisLabel.setObjectName("alongAxisLabel")
        self.gridLayout.addWidget(self.alongAxisLabel, 3, 0, 1, 2)
        self.aroundAxisLabel = QtGui.QLabel(volSpeedAttr)
        self.aroundAxisLabel.setObjectName("aroundAxisLabel")
        self.gridLayout.addWidget(self.aroundAxisLabel, 4, 0, 1, 1)
        self.aroundAxis = QtGui.QDoubleSpinBox(volSpeedAttr)
        self.aroundAxis.setDecimals(3)
        self.aroundAxis.setMinimum(-1000000000.0)
        self.aroundAxis.setMaximum(1000000000.0)
        self.aroundAxis.setObjectName("aroundAxis")
        self.gridLayout.addWidget(self.aroundAxis, 4, 2, 1, 1)
        self.randomDirectionLabel = QtGui.QLabel(volSpeedAttr)
        self.randomDirectionLabel.setObjectName("randomDirectionLabel")
        self.gridLayout.addWidget(self.randomDirectionLabel, 5, 0, 1, 2)
        self.randomDirection = QtGui.QDoubleSpinBox(volSpeedAttr)
        self.randomDirection.setDecimals(3)
        self.randomDirection.setMinimum(-1000000000.0)
        self.randomDirection.setMaximum(1000000000.0)
        self.randomDirection.setObjectName("randomDirection")
        self.gridLayout.addWidget(self.randomDirection, 5, 2, 1, 1)
        self.directionalSpeedLabel = QtGui.QLabel(volSpeedAttr)
        self.directionalSpeedLabel.setObjectName("directionalSpeedLabel")
        self.gridLayout.addWidget(self.directionalSpeedLabel, 6, 0, 1, 1)
        self.directionalSpeed = QtGui.QDoubleSpinBox(volSpeedAttr)
        self.directionalSpeed.setDecimals(3)
        self.directionalSpeed.setMinimum(-1000000000.0)
        self.directionalSpeed.setMaximum(1000000000.0)
        self.directionalSpeed.setObjectName("directionalSpeed")
        self.gridLayout.addWidget(self.directionalSpeed, 6, 2, 1, 1)
        self.scaleSpeedBySize = QtGui.QCheckBox(volSpeedAttr)
        self.scaleSpeedBySize.setObjectName("scaleSpeedBySize")
        self.gridLayout.addWidget(self.scaleSpeedBySize, 7, 0, 1, 3)
        self.displaySpeed = QtGui.QCheckBox(volSpeedAttr)
        self.displaySpeed.setChecked(True)
        self.displaySpeed.setObjectName("displaySpeed")
        self.gridLayout.addWidget(self.displaySpeed, 8, 0, 1, 3)
        self.alongAxis = QtGui.QDoubleSpinBox(volSpeedAttr)
        self.alongAxis.setDecimals(3)
        self.alongAxis.setMinimum(-1000000000.0)
        self.alongAxis.setMaximum(1000000000.0)
        self.alongAxis.setObjectName("alongAxis")
        self.gridLayout.addWidget(self.alongAxis, 3, 2, 1, 1)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 3, 3, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem1, 9, 0, 1, 1)
        self.awayFromAxis = QtGui.QDoubleSpinBox(volSpeedAttr)
        self.awayFromAxis.setDecimals(3)
        self.awayFromAxis.setMinimum(-1000000000.0)
        self.awayFromAxis.setMaximum(1000000000.0)
        self.awayFromAxis.setProperty("value", 1.0)
        self.awayFromAxis.setObjectName("awayFromAxis")
        self.gridLayout.addWidget(self.awayFromAxis, 1, 2, 1, 1)

        self.retranslateUi(volSpeedAttr)
        QtCore.QMetaObject.connectSlotsByName(volSpeedAttr)

    def retranslateUi(self, volSpeedAttr):
        volSpeedAttr.setWindowTitle(QtGui.QApplication.translate("volSpeedAttr", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.awayFromCenterLabel.setText(QtGui.QApplication.translate("volSpeedAttr", "Away From Center", None, QtGui.QApplication.UnicodeUTF8))
        self.awayFromAxisLabel.setText(QtGui.QApplication.translate("volSpeedAttr", "Away From Axis", None, QtGui.QApplication.UnicodeUTF8))
        self.alongAxisLabel.setText(QtGui.QApplication.translate("volSpeedAttr", "Along Axis", None, QtGui.QApplication.UnicodeUTF8))
        self.aroundAxisLabel.setText(QtGui.QApplication.translate("volSpeedAttr", "Around Axis", None, QtGui.QApplication.UnicodeUTF8))
        self.randomDirectionLabel.setText(QtGui.QApplication.translate("volSpeedAttr", "Random Direction", None, QtGui.QApplication.UnicodeUTF8))
        self.directionalSpeedLabel.setText(QtGui.QApplication.translate("volSpeedAttr", "Directional Speed", None, QtGui.QApplication.UnicodeUTF8))
        self.scaleSpeedBySize.setText(QtGui.QApplication.translate("volSpeedAttr", "Scale Speed by Size", None, QtGui.QApplication.UnicodeUTF8))
        self.displaySpeed.setText(QtGui.QApplication.translate("volSpeedAttr", "Display Speed", None, QtGui.QApplication.UnicodeUTF8))

